/**
 * Single-scene rendering: builds ONE ffmpeg invocation that composites a
 * scene's tracks over the project background and mixes its audio.
 *
 * Filtergraph shape (kept deliberately boring):
 *   input 0        lavfi color source  = canvas background, exact scene length
 *   input 1        lavfi anullsrc      = silent stereo base, exact scene length
 *   input 2..N     one input per visual/audio element (media file or a text
 *                  overlay PNG generated by ./text-image)
 *
 *   video: each element is trimmed to its source segment, PTS-reset, rate-
 *   adjusted, scaled to fit the canvas (aspect preserved, even dimensions),
 *   PTS-shifted to its timeline start, then overlaid onto the running
 *   composite gated by enable='between(t,start,end)'.
 *
 *   audio: each audible element is atrim'd, PTS-reset, resampled to a common
 *   48k stereo format, volume/fade-adjusted, adelay'd to its start, and
 *   amix'd with the silent base (base first + duration=first, so the mix
 *   always spans exactly the scene).
 *
 * Text uses drawtext when the local ffmpeg build has it; otherwise the text
 * is rasterized to a PNG with the built-in font and follows the image path.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { mt, sceneDuration } from "@vdx/timeline";
import type {
  ImageElement,
  MediaAsset,
  TextElement,
  TProject,
  TScene,
  VideoElement,
} from "@vdx/timeline";
import { ffmpegHasFilter, probe, run } from "./ffmpeg";
import type { ProbeResult } from "./ffmpeg";
import { encodePng, renderTextImage } from "./text-image";

export interface SceneRenderOptions {
  draft?: boolean;
  /** Stop encoding after this many seconds (used by renderFrame). */
  limitSec?: number;
  /** Directory for generated intermediates (text overlay PNGs). */
  workDir: string;
  onProgress?: (message: string) => void;
}

const DRAFT_WIDTH = 640;

// -- small pure helpers (exported for tests) --------------------------------

/** Seconds with fixed precision for ffmpeg args/expressions. */
export function fmtSec(seconds: number): string {
  return seconds.toFixed(6);
}

/** #RGB/#RRGGBB/#RRGGBBAA → ffmpeg 0x form; named colors pass through. */
export function ffColor(color: string): string {
  const m = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/.exec(color.trim());
  if (!m) return color;
  let hex = m[1];
  if (hex.length === 3) hex = hex.split("").map((c) => c + c).join("");
  return `0x${hex}`;
}

/**
 * Quote a value for use inside a filtergraph option (drawtext text etc.).
 * Wraps in single quotes; embedded quotes close/escape/reopen, backslashes
 * are doubled. Safe against ':' ',' ';' '[' ']' filtergraph metacharacters.
 */
export function escapeFilterValue(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, `'\\''`)}'`;
}

/** Decompose a playback rate into atempo steps (atempo only accepts 0.5–2). */
export function atempoChain(rate: number): string[] {
  if (!(rate > 0)) throw new Error(`Invalid playback rate: ${rate}`);
  if (rate === 1) return [];
  const steps: number[] = [];
  let r = rate;
  while (r < 0.5) {
    steps.push(0.5);
    r /= 0.5;
  }
  while (r > 2) {
    steps.push(2);
    r /= 2;
  }
  if (r !== 1) steps.push(r);
  return steps.map((s) => `atempo=${Number(s.toFixed(6))}`);
}

/** Overlay position: centered on the canvas plus the transform pixel offset. */
function overlayPosition(tx: number, ty: number): string {
  return `x=(W-w)/2+(${tx}):y=(H-h)/2+(${ty})`;
}

function enableWindow(startSec: number, endSec: number): string {
  return `enable='between(t,${fmtSec(startSec)},${fmtSec(endSec)})'`;
}

const FONT_FILE_CANDIDATES = [
  "/System/Library/Fonts/Helvetica.ttc",
  "/System/Library/Fonts/Supplemental/Arial.ttf",
  "/Library/Fonts/Arial.ttf",
  "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
];

/** drawtext filter string for a text element (used when the build has it). */
export function buildDrawtextFilter(
  el: TextElement,
  opts: { startSec: number; endSec: number },
): string {
  const size = Math.max(4, Math.round(el.fontSize * el.transform.scale));
  const parts = [
    `drawtext=text=${escapeFilterValue(el.content)}`,
    "expansion=none",
    `fontsize=${size}`,
    `fontcolor=${ffColor(el.color)}@${el.opacity}`,
    `x=(w-text_w)/2+(${el.transform.x})`,
    `y=(h-text_h)/2+(${el.transform.y})`,
  ];
  if (el.backgroundColor) {
    parts.push("box=1", `boxcolor=${ffColor(el.backgroundColor)}`, `boxborderw=${Math.max(4, Math.round(size / 4))}`);
  }
  const fontFile = FONT_FILE_CANDIDATES.find((f) => existsSync(f));
  if (fontFile) parts.push(`fontfile=${escapeFilterValue(fontFile)}`);
  else parts.push(`font=${escapeFilterValue(el.fontFamily)}`);
  parts.push(enableWindow(opts.startSec, opts.endSec));
  return parts.join(":");
}

// -- scene rendering --------------------------------------------------------

function requireAsset(
  project: TProject,
  mediaId: string,
  elementName: string,
): MediaAsset {
  const asset = project.mediaAssets.find((a) => a.id === mediaId);
  if (!asset) {
    throw new Error(
      `Element "${elementName}" references unknown mediaId "${mediaId}". ` +
        `Known assets: ${project.mediaAssets.map((a) => a.id).join(", ") || "(none)"}`,
    );
  }
  if (!existsSync(asset.src)) {
    throw new Error(`Media file for asset "${asset.name}" not found: ${asset.src}`);
  }
  return asset;
}

/**
 * Render one scene to an MP4 (H.264 + AAC, always with an audio stream).
 * Draft mode downscales to ≤640 wide with faster/cheaper encoding settings.
 */
export async function renderScene(
  project: TProject,
  scene: TScene,
  outPath: string,
  options: SceneRenderOptions,
): Promise<void> {
  const draft = options.draft ?? false;
  const progress = options.onProgress ?? (() => {});
  const { width: W, height: H } = project.settings.canvasSize;
  const fps = `${project.settings.fps.numerator}/${project.settings.fps.denominator}`;

  const durationTicks = sceneDuration(scene);
  if (durationTicks <= 0) {
    throw new Error(`Scene "${scene.name}" (${scene.id}) has no elements — nothing to render`);
  }
  const durationSec = mt.toSeconds(durationTicks);

  mkdirSync(options.workDir, { recursive: true });
  mkdirSync(dirname(resolve(outPath)), { recursive: true });

  const drawtextAvailable = await ffmpegHasFilter("drawtext");
  const probeCache = new Map<string, Promise<ProbeResult>>();
  const probeSrc = (src: string): Promise<ProbeResult> => {
    let cached = probeCache.get(src);
    if (!cached) {
      cached = probe(src);
      probeCache.set(src, cached);
    }
    return cached;
  };

  // input 0: canvas background; input 1: silent audio base — both exactly
  // scene-length so the composite and the mix have a fixed reference span.
  const inputs: string[][] = [
    ["-f", "lavfi", "-i", `color=c=${ffColor(project.settings.background.color)}:s=${W}x${H}:r=${fps}:d=${fmtSec(durationSec)}`],
    ["-f", "lavfi", "-t", fmtSec(durationSec), "-i", "anullsrc=channel_layout=stereo:sample_rate=48000"],
  ];
  const filters: string[] = [];
  const audioLabels: string[] = [];
  let comp = "0:v";
  let compIndex = 0;

  const nextComp = (): string => `comp${++compIndex}`;

  const addVisualOverlay = (
    inputIndex: number,
    elementChain: string[],
    startSec: number,
    endSec: number,
    tx: number,
    ty: number,
  ) => {
    const label = `v${inputIndex}`;
    filters.push(`[${inputIndex}:v]${elementChain.join(",")}[${label}]`);
    const next = nextComp();
    filters.push(
      `[${comp}][${label}]overlay=${overlayPosition(tx, ty)}:eof_action=pass:${enableWindow(startSec, endSec)}[${next}]`,
    );
    comp = next;
  };

  // Fit box for video/image: canvas size times the element's transform scale,
  // aspect preserved, forced even (yuv420p requires even dimensions).
  const fitBox = (scale: number): { w: number; h: number } => ({
    w: Math.max(2, 2 * Math.round((W * scale) / 2)),
    h: Math.max(2, 2 * Math.round((H * scale) / 2)),
  });

  // Visual stacking order: main track at the bottom, then overlay tracks
  // bottom-up (SceneTracks.overlay is listed top-first, hence the reverse).
  const visualTracks = [scene.tracks.main, ...[...scene.tracks.overlay].reverse()].filter(
    (t) => !t.hidden,
  );

  for (const track of visualTracks) {
    const elements = [...track.elements].sort((a, b) => a.startTime - b.startTime);
    for (const el of elements) {
      const startSec = mt.toSeconds(el.startTime);
      const endSec = mt.toSeconds(el.startTime + el.duration);
      const elDurationSec = mt.toSeconds(el.duration);

      if (el.type === "video") {
        const video = el as VideoElement;
        if (video.transform.rotation % 360 !== 0) {
          progress(`Note: rotation on "${video.name}" is not supported yet; ignoring`);
        }
        const asset = requireAsset(project, video.mediaId, video.name);
        const rate = video.rate ?? 1;
        const srcStart = mt.toSeconds(video.trimStart);
        const srcEnd = srcStart + elDurationSec * rate;
        const box = fitBox(video.transform.scale);
        const index = inputs.length;
        inputs.push(["-i", asset.src]);

        const chain = [
          `trim=start=${fmtSec(srcStart)}:end=${fmtSec(srcEnd)}`,
          rate === 1 ? "setpts=PTS-STARTPTS" : `setpts=(PTS-STARTPTS)/${rate}`,
          `fps=${fps}`,
          `scale=w=${box.w}:h=${box.h}:force_original_aspect_ratio=decrease:force_divisible_by=2`,
          "setsar=1",
        ];
        if (video.opacity < 1) chain.push("format=rgba", `colorchannelmixer=aa=${video.opacity}`);
        chain.push(`setpts=PTS+${fmtSec(startSec)}/TB`);
        addVisualOverlay(index, chain, startSec, endSec, video.transform.x, video.transform.y);

        // The element's own audio, when audible and the source has a stream.
        if (track.type === "video" && !track.muted && !video.muted && video.volume > 0) {
          const meta = await probeSrc(asset.src);
          if (meta.hasAudio) {
            const parts = [
              `atrim=start=${fmtSec(srcStart)}:end=${fmtSec(srcEnd)}`,
              "asetpts=PTS-STARTPTS",
              ...atempoChain(rate),
              "aresample=48000",
              "aformat=sample_fmts=fltp:channel_layouts=stereo",
            ];
            if (video.volume !== 1) parts.push(`volume=${video.volume}`);
            const delayMs = Math.round(startSec * 1000);
            if (delayMs > 0) parts.push(`adelay=${delayMs}:all=1`);
            const label = `a${index}`;
            filters.push(`[${index}:a]${parts.join(",")}[${label}]`);
            audioLabels.push(label);
          }
        }
      } else if (el.type === "image") {
        const image = el as ImageElement;
        const asset = requireAsset(project, image.mediaId, image.name);
        const box = fitBox(image.transform.scale);
        const index = inputs.length;
        inputs.push(["-loop", "1", "-framerate", fps, "-t", fmtSec(elDurationSec), "-i", asset.src]);

        const chain = [
          `scale=w=${box.w}:h=${box.h}:force_original_aspect_ratio=decrease:force_divisible_by=2`,
          "setsar=1",
        ];
        if (image.opacity < 1) chain.push("format=rgba", `colorchannelmixer=aa=${image.opacity}`);
        chain.push(`setpts=PTS-STARTPTS+${fmtSec(startSec)}/TB`);
        addVisualOverlay(index, chain, startSec, endSec, image.transform.x, image.transform.y);
      } else if (el.type === "text") {
        const text = el as TextElement;
        if (drawtextAvailable) {
          const next = nextComp();
          filters.push(`[${comp}]${buildDrawtextFilter(text, { startSec, endSec })}[${next}]`);
          comp = next;
        } else {
          // Lean ffmpeg build (no libfreetype): rasterize with the built-in
          // font and overlay the PNG like an image element.
          const image = renderTextImage({
            content: text.content,
            fontSize: Math.max(4, Math.round(text.fontSize * text.transform.scale)),
            color: text.color,
            backgroundColor: text.backgroundColor,
            textAlign: text.textAlign,
          });
          const file = join(options.workDir, `text-${inputs.length}.png`);
          writeFileSync(file, encodePng(image.data, image.width, image.height));
          const index = inputs.length;
          inputs.push(["-loop", "1", "-framerate", fps, "-t", fmtSec(elDurationSec), "-i", file]);

          const chain = ["setsar=1"];
          if (text.opacity < 1) chain.push("format=rgba", `colorchannelmixer=aa=${text.opacity}`);
          chain.push(`setpts=PTS-STARTPTS+${fmtSec(startSec)}/TB`);
          addVisualOverlay(index, chain, startSec, endSec, text.transform.x, text.transform.y);
        }
      }
    }
  }

  // Standalone audio tracks.
  for (const track of scene.tracks.audio) {
    if (track.muted) continue;
    for (const el of [...track.elements].sort((a, b) => a.startTime - b.startTime)) {
      if (el.muted || el.volume <= 0) continue;
      const asset = requireAsset(project, el.mediaId, el.name);
      const startSec = mt.toSeconds(el.startTime);
      const elDurationSec = mt.toSeconds(el.duration);
      const srcStart = mt.toSeconds(el.trimStart);
      const index = inputs.length;
      inputs.push(["-i", asset.src]);

      const parts = [
        `atrim=start=${fmtSec(srcStart)}:end=${fmtSec(srcStart + elDurationSec)}`,
        "asetpts=PTS-STARTPTS",
        "aresample=48000",
        "aformat=sample_fmts=fltp:channel_layouts=stereo",
      ];
      if (el.volume !== 1) parts.push(`volume=${el.volume}`);
      if (el.fadeIn && el.fadeIn > 0) {
        parts.push(`afade=t=in:st=0:d=${fmtSec(mt.toSeconds(el.fadeIn))}`);
      }
      if (el.fadeOut && el.fadeOut > 0) {
        const fadeSec = mt.toSeconds(el.fadeOut);
        parts.push(`afade=t=out:st=${fmtSec(Math.max(0, elDurationSec - fadeSec))}:d=${fmtSec(fadeSec)}`);
      }
      const delayMs = Math.round(startSec * 1000);
      if (delayMs > 0) parts.push(`adelay=${delayMs}:all=1`);
      const label = `a${index}`;
      filters.push(`[${index}:a]${parts.join(",")}[${label}]`);
      audioLabels.push(label);
    }
  }

  // Final video: force even dimensions and yuv420p; draft downscales.
  const finalScale = draft
    ? `scale='trunc(min(${DRAFT_WIDTH},iw)/2)*2':-2`
    : "scale=trunc(iw/2)*2:trunc(ih/2)*2";
  filters.push(`[${comp}]${finalScale},format=yuv420p[vout]`);

  // Final audio: silent base first + duration=first pins the mix to the
  // scene length; normalize=0 keeps element volumes as authored.
  if (audioLabels.length > 0) {
    filters.push(
      `[1:a]${audioLabels.map((l) => `[${l}]`).join("")}amix=inputs=${audioLabels.length + 1}:duration=first:normalize=0[aout]`,
    );
  } else {
    filters.push("[1:a]anull[aout]");
  }

  const encodeSec = options.limitSec !== undefined ? Math.min(durationSec, options.limitSec) : durationSec;
  const args = [
    "-y",
    ...inputs.flat(),
    "-filter_complex", filters.join(";"),
    "-map", "[vout]",
    "-map", "[aout]",
    "-r", fps,
    "-t", fmtSec(encodeSec),
    "-c:v", "libx264",
    "-preset", draft ? "ultrafast" : "veryfast",
    "-crf", draft ? "30" : "23",
    "-pix_fmt", "yuv420p",
    "-movflags", "+faststart",
    "-c:a", "aac",
    "-b:a", "128k",
    "-ar", "48000",
    outPath,
  ];

  progress(`ffmpeg: scene "${scene.name}" (${fmtSec(encodeSec)}s, ${inputs.length} inputs)`);
  await run(args);
}
